DBSD_CW2/Controllers/PositionsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBSD_CW2.DAL;
using DBSD_CW2.Models;

namespace DBSD_CW2.Controllers
{
    public class PositionsController : Controller
    {
        private IRepository _DbManager;
        private Position _model;

        public PositionsController(IRepository repository)
        {
            _DbManager = repository;
            _model = new Position();
        }
        // GET: PositionsController
        public ActionResult Index()
        {
            var listOfPositions = _DbManager.GetAllProcedure<Position>(_model);
            return View(listOfPositions);
        }

        // GET: PositionsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PositionsController/Create
        public ActionResult Create()
        {
            ViewBag.ErrorMessage = "";
            return View();
        }

        // POST: PositionsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Position position)
        {
            try
            {
                _DbManager.InsertOneProcedure<Position>(_model, new { PositionName = position.PositionName });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMessage = "Probably PositionName is too short, at least 3 chars needed";
                return View();
            }
        }

        // GET: PositionsController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.ErrorMessage = "";
            return View(_DbManager.GetOneProcedure<Position>(_model, new { PositionId = id }));
        }

        // POST: PositionsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Position position)
        {
            try
            {
                _DbManager.UpdateOneProcedure<Position>(_model, new
                {
                    PositionName = position.PositionName,
                    PositionId = position.PositionId
                });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMessage = "Probably PositionName is too short, at least 3 chars needed";
                return View();
            }
        }

        // GET: PositionsController/Delete/5
        public ActionResult Delete(int id)
        {
            _DbManager.DeleteOneProcedure<Position>(_model, new { PositionId = id });
            return RedirectToAction(nameof(Index));
        }
    }
}

DBSD_CW2/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBSD_CW2.DAL;
using DBSD_CW2.Models;

namespace DBSD_CW2.Controllers
{
    public class ProjectsController : Controller
    {
        private IRepository _DbManager;
        private Project _model;

        public ProjectsController(IRepository repository)
        {
            _DbManager = repository;
            _model = new Project();
        }
        // GET: ProjectController
        public ActionResult Index()
        {
            var listOfProjects = _DbManager.GetAllProcedure<Project>(_model);
            return View(listOfProjects);
        }

        // GET: ProjectController/Create
        public ActionResult Create()
        {
            ViewBag.ErrorMessage = "";
            return View();
        }

        // POST: ProjectController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project)
        {
            try
            {
                _DbManager.InsertOneProcedure<Project>(project, new { projectName = project.ProjectName });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMessage = "Probably ProjectName is too short, at least 3 chars needed";
                return View();
            }
        }

        // GET: ProjectController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_DbManager.GetOneProcedure<Project>(_model, new { ProjectId = id }));
        }

        // POST: ProjectController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            try
            {
                ViewBag.ErrorMessage = "";
                _DbManager.UpdateOneProcedure<Project>(project, new {
                    ProjectName = project.ProjectName,
                    ProjectId = project.ProjectId
                });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMessage = "Probably ProjectName is too short, at least 3 chars needed";
                return View();
            }
        }

        // GET: ProjectController/Delete/5
        public ActionResult Delete(int id)
        {
            _DbManager.DeleteOneProcedure<Project>(_model, new { ProjectId = id });
            return RedirectToAction(nameof(Index));
        }
    }
}

DBSD_CW2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DBSD_CW2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Filter">DBSD_CW2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Filter">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">Positions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DBSD_CW2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>